import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Products from "@/components/Products/Products";
import Sidebar from "@/components/Sidebar/Sidebar";
import { useReducer } from "react";
import { categoryReducer,ratingReducer } from "@/reducers/modifyProductsReducer";
import { CategoryContext,RatingContext } from "@/context/ModifyProductsContext";


export default function Home() {

  const [category,categoryDispatch] = useReducer(categoryReducer,'All');
  const [rating,ratingDispatch] = useReducer(ratingReducer,'All');

  console.log(category);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CategoryContext.Provider value={{category,categoryDispatch}}>
          <RatingContext.Provider value={{rating,ratingDispatch}}>
            <Sidebar  />
            <Products />
          </RatingContext.Provider>
        </CategoryContext.Provider>
      </div> 
    </>
  );
}
